### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by remb0** [OH-Jython-Scripters/ideAlarm#1]
This alarm script looks like ideAlarm for another platform.   is that code/wiki still available? I really want to get a copy so I can continue this great work for a lot of users..

I hope the documentation is still available somewhere.   can you help me?

**Comment by besynnerlig** [comment]
I'm sorry to inform that there are no copies of that Wiki. Prior deletion there was an open request on that other platforms forum for a new maintainer. Unfortunately no one showed any interest at that time. The repository has been forked a few times before deletion. Maybe someone else keeps a copy of it.
